import 'package:flutter/material.dart';

import 'app_colors.dart';

abstract class AppTypography {
  static const String fontFamily = 'Cairo';
  static const List<String> fallbackFamily = [
    'Tajawal',
    'Noto Sans Arabic',
    'Noto Naskh Arabic',
    'sans-serif',
  ];

  static TextTheme textThemeLight(TextTheme base) {
    return base.copyWith(
      displayLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 32,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryLight,
        height: 1.25,
      ),
      displayMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 28,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryLight,
        height: 1.3,
      ),
      displaySmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 24,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryLight,
        height: 1.3,
      ),
      headlineLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 22,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryLight,
        height: 1.3,
      ),
      headlineMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 20,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryLight,
        height: 1.35,
      ),
      headlineSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 18,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryLight,
        height: 1.35,
      ),
      titleLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 17,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryLight,
        height: 1.4,
      ),
      titleMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 15,
        fontWeight: FontWeight.w600,
        color: AppColors.textPrimaryLight,
        height: 1.4,
      ),
      titleSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        color: AppColors.textPrimaryLight,
        height: 1.4,
      ),
      bodyLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 15,
        fontWeight: FontWeight.w500,
        color: AppColors.textPrimaryLight,
        height: 1.5,
      ),
      bodyMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 13,
        fontWeight: FontWeight.w400,
        color: AppColors.textSecondaryLight,
        height: 1.5,
      ),
      bodySmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        color: AppColors.textMutedLight,
        height: 1.5,
      ),
      labelLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 14,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryLight,
        height: 1.3,
      ),
      labelMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 12,
        fontWeight: FontWeight.w600,
        color: AppColors.textSecondaryLight,
        height: 1.3,
      ),
      labelSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 11,
        fontWeight: FontWeight.w600,
        color: AppColors.textMutedLight,
        height: 1.3,
      ),
    );
  }

  static TextTheme textThemeDark(TextTheme base) {
    return base.copyWith(
      displayLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 32,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryDark,
        height: 1.25,
      ),
      displayMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 28,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryDark,
        height: 1.3,
      ),
      displaySmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 24,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryDark,
        height: 1.3,
      ),
      headlineLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 22,
        fontWeight: FontWeight.w800,
        color: AppColors.textPrimaryDark,
        height: 1.3,
      ),
      headlineMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 20,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryDark,
        height: 1.35,
      ),
      headlineSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 18,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryDark,
        height: 1.35,
      ),
      titleLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 17,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryDark,
        height: 1.4,
      ),
      titleMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 15,
        fontWeight: FontWeight.w600,
        color: AppColors.textPrimaryDark,
        height: 1.4,
      ),
      titleSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 14,
        fontWeight: FontWeight.w600,
        color: AppColors.textPrimaryDark,
        height: 1.4,
      ),
      bodyLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 15,
        fontWeight: FontWeight.w500,
        color: AppColors.textPrimaryDark,
        height: 1.5,
      ),
      bodyMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 13,
        fontWeight: FontWeight.w400,
        color: AppColors.textSecondaryDark,
        height: 1.5,
      ),
      bodySmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        color: AppColors.textMutedDark,
        height: 1.5,
      ),
      labelLarge: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 14,
        fontWeight: FontWeight.w700,
        color: AppColors.textPrimaryDark,
        height: 1.3,
      ),
      labelMedium: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 12,
        fontWeight: FontWeight.w600,
        color: AppColors.textSecondaryDark,
        height: 1.3,
      ),
      labelSmall: const TextStyle(
        fontFamily: fontFamily,
        fontFamilyFallback: fallbackFamily,
        fontSize: 11,
        fontWeight: FontWeight.w600,
        color: AppColors.textMutedDark,
        height: 1.3,
      ),
    );
  }
}
