ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'SUPERVISOR_VISIT_ASSIGNED';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'STAFF_SHIFT_REMINDER';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'STAFF_LATE_ALERT';
