import type { ReactNode } from "react";
import { useI18n } from "../../../app/i18n";

export type SignatureRole = {
  label: string;
  name?: string;
};

export type PrintableReportTemplateProps = {
  title: string;
  subtitle?: string;
  organizationName?: string;
  logoUrl?: string;
  period?: string;
  reportNumber?: string;
  printedBy?: string;
  summary?: ReactNode;
  children: ReactNode;
  notes?: string;
  signatures?: SignatureRole[];
  showFooter?: boolean;
  className?: string;
};

function formatDate(ar: boolean): string {
  const d = new Date();
  try {
    return d.toLocaleDateString(ar ? "ar-SA" : "en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return d.toISOString().slice(0, 10);
  }
}

export function PrintableReportTemplate({
  title,
  subtitle,
  organizationName,
  logoUrl,
  period,
  reportNumber,
  printedBy,
  summary,
  children,
  notes,
  signatures,
  showFooter = true,
  className = "",
}: PrintableReportTemplateProps) {
  const { language } = useI18n();
  const ar = language === "ar";
  const printDate = formatDate(ar);

  const defaultOrgName = organizationName || (ar ? "جمعية رفقاء القرآن" : "Rafiq Al-Quran Association");
  const defaultSignatures: SignatureRole[] = signatures ?? [
    { label: ar ? "إعداد" : "Prepared by" },
    { label: ar ? "مراجعة" : "Reviewed by" },
    { label: ar ? "اعتماد" : "Approved by" },
  ];

  return (
    <div className={`print-only print-template ${className}`} dir={ar ? "rtl" : "ltr"}>
      {/* Report Header */}
      <div className="print-report-header">
        <div className="logo-area">
          {logoUrl && (
            <img
              src={logoUrl}
              alt={ar ? "شعار" : "Logo"}
              style={{ height: 48, margin: "0 auto 4px" }}
            />
          )}
          <h1>{organizationName || defaultOrgName}</h1>
          <p>{subtitle || ""}</p>
        </div>
        <div className="meta-area">
          <div>
            <strong>{ar ? "التقرير:" : "Report:"}</strong> {title}
          </div>
          {period && (
            <div>
              <strong>{ar ? "الفترة:" : "Period:"}</strong> {period}
            </div>
          )}
          {reportNumber && (
            <div>
              <strong>{ar ? "رقم التقرير:" : "Report No.:"}</strong> {reportNumber}
            </div>
          )}
          <div>
            <strong>{ar ? "تاريخ الطباعة:" : "Print Date:"}</strong> {printDate}
          </div>
          {printedBy && (
            <div>
              <strong>{ar ? "طباع بواسطة:" : "Printed by:"}</strong> {printedBy}
            </div>
          )}
        </div>
      </div>

      {/* Summary */}
      {summary && <div className="print-summary">{summary}</div>}

      {/* Detail Content */}
      <div className="print-content">{children}</div>

      {/* Notes */}
      {notes && (
        <div className="print-notes" style={{ marginTop: 16, fontSize: "9pt", color: "#6b7280" }}>
          <strong>{ar ? "ملاحظات:" : "Notes:"}</strong>
          <p style={{ margin: "4px 0" }}>{notes}</p>
        </div>
      )}

      {/* Signatures */}
      <div className="print-signatures">
        {defaultSignatures.map((sig, i) => (
          <div key={i} className="print-signature-box">
            <strong>{sig.label}</strong>
            {sig.name && <span>{sig.name}</span>}
          </div>
        ))}
      </div>

      {/* Footer */}
      {showFooter && (
        <div className="print-report-footer">
          <span>
            {ar
              ? "تم إنشاء التقرير بواسطة نظام رفقاء القرآن — هذا التقرير صادر آليًا ولا يعتمد دون توقيع الإدارة عند الحاجة"
              : "Generated by Rafiq Al-Quran System — This report is automatically generated and requires management signature when needed"}
          </span>
          <span style={{ margin: ar ? "0 16px 0 0" : "0 0 0 16px" }}>
            {ar ? "صفحة" : "Page"}{" "}<span className="page-number" />
          </span>
        </div>
      )}
    </div>
  );
}

/**
 * Utility: trigger browser print with the given element ref or the whole page.
 * Uses window.print() — hides interactive elements via CSS @media print.
 */
export function triggerPrint() {
  window.print();
}

export default PrintableReportTemplate;
